### ISSUE TITLE
score of text prompt only

### ISSUE THREAD

**Issue by thunderofdream** [ThuCCSLab/FigStep#4]
Hello, I am very interested in your research. Can you provide detailed scores for each question in Figure 3 (text prompt only) of your paper? Just like the files in the directory data/result/score

**Comment by YichenBC** [comment]
Thank you for your interest in our work. Kindly remind that we have updated our technical report. In fact our newest version uses manual review as the evaluator to judge whether the responses violate policy. So the score of some response is 0 or 1. The original results varing from 1 to 5 are deprecated. If you would like to receive the detailed statistics, please reply your institution e-mail (since the results contain harmful model responses), thanks!

**Comment by thunderofdream** [comment]
Thank you for your reply. My email is 332210030763@email.zzuli.edu.cn，
Additionally, I still hope to receive results varying from 1 to 5

**Comment by YichenBC** [comment]
Thanks for your patience. I sent an email to the address you provided. All good wishes.

**Comment by thunderofdream** [comment]
Thank you very much for your help. I have received your email and wish you all the best in your work
